//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billingapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> prod_qty { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
